"$schema" = "./node_modules/wrangler/config-schema.json"
name = "my-worker"
main = "/index.html"
compatibility_date = "2026-02-05"
workers_dev = false

[route]
pattern = "saularchives.com/*"
zone_name = "saularchives.com"

[[kv_namespaces]]
binding = "<MY_NAMESPACE>"
id = "<KV_ID>"

[env.staging]
name = "my-worker-staging"

  [env.staging.route]
  pattern = "staging.example.org/*"
  zone_name = "saularchives.com"

  [[env.staging.kv_namespaces]]
  binding = "<MY_NAMESPACE>"
  id = "<STAGING_KV_ID>"